apiVersion: 1

datasources:
  - name: RequestLogs
    type: frser-sqlite-datasource
    access: proxy
    jsonData:
      path: /var/lib/grafana/logs/requests.db
    isDefault: true
    editable: false
